name: Generate and Deploy RSS Feed

on:
  schedule:
    - cron: '0 */2 * * *'    # Every 2 hours 
    - cron: '0 */12 * * *'   # Every 12 hours 
  workflow_dispatch:

jobs:
  generate_feed:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Hong_Kong  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Initialize gh-pages branch
        run: |
          # Check if branch exists remotely
          if ! git ls-remote --exit-code --heads origin gh-pages; then
            echo "Creating gh-pages branch..."
            git checkout --orphan gh-pages
            git rm -rf .
            echo "Initial commit" > index.html
            git add index.html
            git commit -m "Initialize gh-pages"
            git push origin gh-pages
            git checkout main
          fi

      - name: Prepare deployment
        run: |
          # Remove any existing deployment directory
          rm -rf gh-pages-deploy || true
          
          # Fetch the gh-pages branch
          git fetch origin gh-pages:gh-pages --force
          
          # Create fresh deployment directory
          mkdir -p gh-pages-deploy
          git --work-tree=gh-pages-deploy checkout gh-pages -- .

      - name: Cache pip dependencies
        uses: actions/cache@v3
        id: pip-cache
        with:
          path: |
            ~/.cache/pip
            venv/
          key: pip-${{ hashFiles('requirements.txt') }}-${{ runner.os }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Generate RSS feeds
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            python hkdiscuss.py --feeds money house
          elif [[ "${{ github.event.schedule }}" == "0 */2 * * *" ]]; then
            python hkdiscuss.py --feeds money house
            python hknet.py
          else
            python hkdiscuss.py --feeds hottopics
          fi

      - name: Deploy to GitHub Pages
        run: |
          # Remove any existing worktree
          git worktree remove gh-pages-deploy --force || true
          
          # Create new worktree
          git worktree add gh-pages-deploy gh-pages
          
          # Move generated files
          mv *.xml gh-pages-deploy/
          
          # Commit and push changes
          cd gh-pages-deploy
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update feeds $(date +'%Y-%m-%d %H:%M:%S')"
            git push origin gh-pages
          fi
