name: Generate and Deploy RSS Feed

on:
  schedule:
    - cron: '0 */2 * * *'    # Every 2 hours
    - cron: '0 */12 * * *'   # Every 12 hours
  workflow_dispatch:

jobs:
  generate_feed:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Hong_Kong

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Initialize gh-pages branch
        run: |
          if ! git ls-remote --exit-code --heads origin gh-pages; then
            echo "Creating gh-pages branch..."
            git checkout --orphan gh-pages
            git rm -rf .
            echo "Initial commit" > index.html
            git add index.html
            git commit -m "Initialize gh-pages"
            git push origin gh-pages
            git checkout main
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Checkout gh-pages branch
          git checkout gh-pages

          # Pull latest changes
          git pull origin gh-pages

          # Generate RSS feeds
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            python hkdiscuss.py --feeds money house hottopics
            python hknet.py
          elif [[ "${{ github.event.schedule }}" == "0 */2 * * *" ]]; then
            python hkdiscuss.py --feeds money house
            python hknet.py
          else
            python hkdiscuss.py --feeds hottopics
          fi

          # Verify XML generation
          echo "Generated files:"
          ls -la
          echo "XML files:"
          ls -la *.xml || echo "No XML files found"

          # Move generated XML files
          rm -rf *.xml # Remove existing xml files
          mv *.xml .

          # Add and commit changes
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Update feeds $(date +'%Y-%m-%d %H:%M:%S')"
            git push origin gh-pages
          fi
